### ISSUE TITLE
Roaming script network interfaces are VirtualBox specific

### ISSUE THREAD

**Issue by akarasulu** [subutai-io/snap#176]
The roaming script interfaces are not going to work on other hypervisors. They're dependent on interface names that will change across them: i.e. enp0s3 etc. The roaming script's goal is to change the default gateway based on the availability of a dhcp server responding on any one of the available links. The script can easily be modified to work on any hypervisor where these names will change.

**Comment by Dilshat** [comment]
After researching and doing multiple tests I came to a simple solution (probably not the best) which has the following assumptions:
1) There are 3 interfaces with the same prefix e.g: **enp, ens, eno, eth**. See https://en.wikipedia.org/wiki/Consistent_Network_Device_Naming
2) First interface is bridged and is primary one that gets added as default route, 2nd is respectively NAT, and 3rd is Host-Only (which is the atm with both vagrant and autobuild approaches)

Script would scan existing interfaces and filter out three with the same prefix.
If there are less than similar 3 interfaces, script just skips the operation.
Otherwise it uses the current implementation of roaming script with the difference that it substitutes the names of interfaces instead of using the hardcoded ones

**Comment by akarasulu** [comment]
Thanks for the extra detail. We have to just stop hardcoding. I thought we removed this hardcoding with your changes. I have to look at the code again.

Why does order matter? Why should it? I seems to me to be a shortcoming of this script. Can you clarify that? 

Also this is the only thing that cares about the order of interfaces right? Everything else does not?
