### ISSUE TITLE
Containers can not be started after peer reboot

### ISSUE THREAD

**Issue by Dilshat** [subutai-io/snap#224]
Sometimes when a peer with existing containers is rebooted, agent can not start some of the containers.
In logs there is a such message:
```
BTRFS error (device dm-6): parent transid verify failed on 1021329408 wanted 2202 found 2976
```

**Comment by happyaron** [comment]
This error is caused by an unexpected interruption (i.e. shutdown/reboot) in the middle of a write operation has been in the log but the actual write hasn't been flushed to disk. For example in
```BTRFS error (device dm-6): parent transid verify failed on 1021329408 wanted 2202 found 2976```
It means 
`1021329408` is the byte offset of the metadata block
`2202` expected generation of the block 
`2976` generation found in the block

To avoid such problem we need to shutdown all the containers and umount the filesystem when the system reboots to make sure we are having a cold environment before power cycle. For current broken file systems we are able to use `btrfs-zero-log` to clear those logs, but there are risks of lost some writes (but the files shouldn't be broken, just some changes aren't there).

**Comment by Dilshat** [comment]
In some cases container can not start and there are these logs:
```
Jan 18 06:01:32 subutai systemd-udevd[9801]: Could not generate persistent MAC address for vethSMTWIB: No such file or directory
Jan 18 06:01:32 subutai ovs-vsctl: ovs|00001|vsctl|INFO|Called as ovs-vsctl add-port lxcbr0 veth29E294
Jan 18 06:01:32 subutai ovs-vsctl: ovs|00002|db_ctl_base|ERR|no bridge named lxcbr0
Jan 18 06:01:32 subutai systemd-udevd[9826]: Could not generate persistent MAC address for vethTNVM5P: No such file or directory
Jan 18 06:01:32 subutai systemd-udevd[9827]: Could not generate persistent MAC address for vethJNDS3W: No such file or directory
Jan 18 06:01:32 subutai ovs-vsctl: ovs|00001|vsctl|INFO|Called as ovs-vsctl add-port lxcbr0 vethJNDS3W
Jan 18 06:01:32 subutai ovs-vsctl: ovs|00002|db_ctl_base|ERR|no bridge named lxcbr0
```

**Comment by Dilshat** [comment]
Related to https://github.com/subutai-io/agent/issues/270

**Comment by amol4anoff** [comment]
Ok, a container is running after a reboot.
