### ISSUE TITLE
Disable btrfs quotas in btrfsinit script

### ISSUE THREAD

**Issue by Dilshat** [subutai-io/snap#233]
we need to remove btrfs enable command from btrfs init script

**Comment by happyaron** [comment]
Talked with @lbthomsen and @Dilshat , it turns out we still want btrfs quota to act as a last resort of keeping the RH environment safe - if a misbehaving container fills disk space quickly between our check intervals we can still stop it with btrfs quota, and on normal containers this limit will be never reached as we are deploying regular space check.

**Comment by Dilshat** [comment]
Ok closing the issue
