### ISSUE TITLE
libcgmanager-dev  on Ubuntu 17.10

### ISSUE THREAD

**Issue by liquuid** [subutai-io/snap#85]
Hi, i couldn't build snap subutai-agent package on ubuntu 17.10:

`Could not find a required package in 'build-packages': libcgmanager-dev`

libcgmanager-dev is not available on ubuntu anymore.

Any ideas ?

**Comment by Dilshat** [comment]
For now you can  build on ubuntu16 until we can figure out what dependencies to use

**Comment by lbthomsen** [comment]
I will check on the Ubuntu 17.10 issue.  Meanwhile, if you do have Docker installed, a quick solution would be to do what I did when I had to build it on a Debian system.  Rather than hacking Debian to work I created a complete environment.

Described (badly) here: https://github.com/lbthomsen/docker-snapcraft
